services: 
  database:
    container_name: postgres-yourtask
    image: postgres:16-alpine3.20
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"