services: 
  database:
    container_name: postgres-dev
    image: postgres:17.2-alpine
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"